name: Test

on:
  push:
    branches:
      - master

jobs:

  cucumber:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: ./mvnw -B clean test --file pom.xml

    - name: Generate Cluecumber report
      run: ./mvnw -B cluecumber-report:reporting --file pom-cluecumber.xml

    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: les-projets-cagnottes/les-projets-cagnottes.github.io
        token: ${{ secrets.GITHUB_IO_PAT }}
        path: les-projets-cagnottes.github.io

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git rev-parse --abbrev-ref HEAD)

    - name: Clean previous version
      run: rm -rf les-projets-cagnottes.github.io/${{ steps.get_version.outputs.VERSION }}/cucumber

    - name: Prepare Cucumber output directory
      run: mkdir -p les-projets-cagnottes.github.io/${{ steps.get_version.outputs.VERSION }}/cucumber

    - name: Copy Cucumber Report
      run: cp -r target/cluecumber/* les-projets-cagnottes.github.io/${{ steps.get_version.outputs.VERSION }}/cucumber/

    - name: Publish https://les-projets-cagnottes.github.io/${{ steps.get_version.outputs.VERSION }}/cucumber
      run: |
        cd les-projets-cagnottes.github.io
        git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}" && git config user.name "${{ secrets.GIT_CONFIG_NAME }}"
        git status
        git add .
        git commit --allow-empty -m "Update Cucumber for version '${{ steps.get_version.outputs.VERSION }}'"
        git push
